<?php

// Строка - обозначение регионов и нац. валют.
define('GF_STOCK_REGION_ALL', 'all');
define('GF_STOCK_REGION_RU', 'Russia');
define('GF_STOCK_REGION_CN', 'China');
define('GF_STOCK_CURRENCY_CN', 'юан');
define('GF_STOCK_CURRENCY_RU', 'руб');


/**
 * Переводим в нужную валюту(соответственно настроек) региональные ценники.
 */
function _gf_stock_convert_to_default_currency($sum, $sum_currency){
  $default_currency = drupal_strtolower(variable_get('gf_stock_region_price_currency', 
    GF_STOCK_CURRENCY_CN));
  $sum_currency = drupal_strtolower($sum_currency);
  if ($default_currency !== $sum_currency) {
    $exchange_rate = variable_get('gf_stock_yuan_exchange_rate');
    switch ($default_currency) {
    case GF_STOCK_CURRENCY_CN:
     return ($sum / $exchange_rate);
    case GF_STOCK_CURRENCY_RU:
     return ($sum * $exchange_rate);
    }
  }
  return $sum;
}


/**
 * Implements hook_importkit_price().
 */
function gf_stock_importkit_price($entity, $xml_element){
  // Обновление/импорт данных о ценах по регионам.
  $prices = $xml_element->Цены->Цена;
  foreach ($prices as $price) {
    db_merge('gf_stock_prices')
      ->key(array(
        'nid' => $entity->nid,
        'price_id' => $price->ИдТипаЦены)
      )->fields(array(
        'price' => $price->ЦенаЗаЕдиницу,
        'currency' => $price->Валюта,
      ))
      ->execute();
  }
}


/**
 * Implements hook_node_delete().
 */
function gf_stock_node_delete($node) {
  // При удалении ноды удаляем запись с оной из таблицы
  // с ценами регионов.
  db_delete('gf_stock_prices')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_importkit_stock().
 */
function gf_stock_importkit_stock($entity, $xml_element){
  $import_started = &drupal_static('gf_stock_import_started');

  if (!$import_started) {
    // Удаляем текущие данные по остаткам в начале импорта.
    db_truncate('gf_stock_stocks')->execute();
    $import_started = TRUE;
  }

  // Обновляем при импорте данные по остаткам в регионах.
  foreach($xml_element->Остатки->ОстаткиСклада as $element) {
    // Запись в таблицу importkit_cml_stock оставляем на
    // случай ее использования другими неведомыми модулями.
    // В нашем она будет нафиг не нужна.
    db_merge('importkit_cml_stock')->key(array(
      'guid1' => $entity->guid1,
      'guid2' => $entity->guid2,
      'nid' => $entity->nid,
      'warehouse' => (string) $element->ИдСклада,
    ))->fields(array(
      'stock' => (string) $element->Остаток,
      'warehouse' => (string) $element->ИдСклада,
      'region' => (string) $element->Регион,
    ))->execute();

    // Запись непосредственно в таблицу, которая будет
    // использоваться в дальнейшем для отображения остатков по регионам.
    db_merge('gf_stock_stocks')
      ->key(array(
        'nid' => $entity->nid,
        'region' => $element->Регион,
      ))
      ->fields(array(
          'stock' => $element->Остаток,
      ))
      ->expression('stock', 'stock + :inc', array(':inc' => $element->Остаток))
      ->execute();

  }
}


/**
 * Implements hook_node_load().
 */
function gf_stock_node_load($nodes, $types){
  if (!count(array_intersect(uc_product_types(), $types))) return;

  $result = db_query("SELECT nid, stock, region
    FROM {gf_stock_stocks}
    WHERE nid IN(:nids)", array(':nids' => array_keys($nodes),));

  // Добавляем при загрузке нод-товаров поля с данными
  // по остаткам в регионах.
  foreach ($result as $record) {
    // Складываем суммы остатков в конкретном регионе для разных представлений.
    $nodes[$record->nid]->gf_region_stock[$record->region] = (int) $record->stock;
  }

  $prices = db_select('gf_stock_prices', 'p')
    ->fields('p', array('nid', 'price','price_id', 'currency'))
    ->condition('nid', array_keys($nodes), 'IN')
    ->execute()
    ->fetchAllAssoc('price_id');

  $price_map = _gf_stock_get_region_price_map();
  foreach ($prices as $price_id=>$price) {
    $price_value = _gf_stock_convert_to_default_currency((double) $price->price, 
        $price->currency);
    $nodes[$prices[$price_id]->nid]->gf_region_prices[$price_map[$price_id]] = $price_value;
  }
}

/**
 * Функция-хелпер для получения 
 * массива код_цены_региона=>индекс_региона('ru' или 'cn').
 */
function _gf_stock_get_region_price_map(){
  $result = [];
  foreach(array_keys(gf_stock_get_regions()) as $region) {
    $price_id = variable_get('gf_stock_region_price_' . $region);
    $result[$price_id] = $region;
  }
  return $result;
}

/**
 * Implements hook_menu().
 */
function gf_stock_menu() {
  // Линк для переключения региона пользователя.
  $items['gf_stock/region_switch'] = array(
    'title' => 'Stock Region Switcher',
    'page callback' => 'gf_stock_region_switch',
    'page arguments' => array(2),
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );
  // Страница настроек модуля.
  $items['admin/importkit/gf_stock'] = array(
    'title' => t('GF Stock'),
    'description' => 'GF Stock module settings',
    'access arguments' => array('administer importkit'),
    'page callback' => 'drupal_get_form',
    'page arguments' => ['gf_stock_settings'],
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  return $items;
}


/**
 * Массив со списком доступных регионов.
 */
function gf_stock_get_regions() {
  return [
    GF_STOCK_REGION_CN => GF_STOCK_REGION_CN,
    GF_STOCK_REGION_RU => GF_STOCK_REGION_RU
  ];

}


/**
 * Переключение региона пользователя.
 */
function gf_stock_region_switch($region=''){
  if ($region) {
    $regions = gf_stock_get_regions();
    if (!in_array($region, $regions)) return;
    else {
      // Метку о выбранном регионе кладем пользователю в сессию.
      $_SESSION['gf_stock_region'] = $regions[$region];
    }
  }
  // Если регион не получе - обнуляем параметр в сессии.
  elseif (isset($_SESSION['gf_stock_region'])) {
    unset($_SESSION['gf_stock_region']);
  }
  drupal_goto();
}


/**
 * Implements hook_block_info().
 *
 */
function gf_stock_block_info() {
  $blocks['gf_stock_region_switch'] = array(
    'info' => t('GF Stock: user region switcher'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 */
function gf_stock_block_view($delta = '') {
  switch ($delta) {
  case 'gf_stock_region_switch':
    $block['subject'] = t('Select warehouse region');
    $block['content'] = gf_stock_block_contents($delta);
    break;
  }
  return $block;
}

/**
 * Формируем содержимое для объявленных в модуле блоков.
 */
function gf_stock_block_contents($block) {
  switch ($block) {
  case 'gf_stock_region_switch':
    $regions = [];

    $region_switch_path = 'gf_stock/region_switch';
    $link_options = [
      'query' => drupal_get_destination(),
      'html' => true,
    ];

    //$regions[GF_STOCK_REGION_ALL] = l(t('All'), $region_switch_path, $link_options);

    foreach(array_keys(gf_stock_get_regions()) as $region) {
      $regions[$region] = l(t($region), $region_switch_path . '/' . $region, $link_options);
    }
    return theme('gf_stock_block_region_switcher', [
      'regions' => $regions,
      'current_region' => gf_stock_get_current_region()
    ]);
  }
}


/**
 * Возврат текущего региона пользователя.
 */
function gf_stock_get_current_region() {
  $default_region = variable_get('gf_stock_default_region', GF_STOCK_REGION_ALL);
  return isset($_SESSION['gf_stock_region']) ? $_SESSION['gf_stock_region'] : $default_region;
}


/**
 * Implements hook_theme().
 */
function gf_stock_theme($existing, $type, $theme, $path) {
  return [
    'gf_stock_block_region_switcher' => [
      'variables' => [
        'regions' => [],
        'current_region' => NULL,
      ],
      'path' => drupal_get_path('module', 'gf_stock') . '/theme',
      'template' => 'gf_stock_block_region_switcher',
    ],
  ];

}


/**
 * Форма наcтроек модуля.
 */
function gf_stock_settings() {
  $rate_array = array(variable_get('gf_stock_yuan_exchange_rate', NULL), 
  variable_get('gf_stock_yuan_rate_last_update', NULL));
  if(in_array(NULL, $rate_array)) {
    gf_stock_update_yuan_exchange_rate(); 
  }

  $form['gf_stock_currency'] = array(
    '#type' => 'fieldset',
    '#title' => t('Basic Currency Settings')
  );
  // Информация о текущем курсе юаня к рублю.
  $form['gf_stock_currency']['gf_stock_current_yuan_exchange_rate'] = array(
    '#markup' => t('The current exchange rate of the yuan to the 
    ruble is @rate rubles per 1 yuan. Date of last update: @date',
array(
  '@rate' => variable_get('gf_stock_yuan_exchange_rate'),
  '@date' => variable_get('gf_stock_yuan_rate_last_update')
)),
  );

// Выбор валюты по-умолчанию.
$form['gf_stock_currency']['gf_stock_region_price_currency'] = array(
  '#type' => 'select',
  '#title' => t('Default currency'),
  '#description' => t('The currency in which the imported prices will be stored.'),
  '#options' => array(
    GF_STOCK_CURRENCY_CN => t('Yuan'),
    GF_STOCK_CURRENCY_RU => t('Ruble')
  ),
  '#default_value' => variable_get('gf_stock_region_price_currency', GF_STOCK_CURRENCY_CN),
);

$form['gf_stock_region_prices'] = array(
  '#type' => 'fieldset',
  '#title' => t('Prices by region'),
);
$options = [];
$options[GF_STOCK_REGION_ALL] = t('All');

// Получаем список ID для цен регионов.
$query_region_ids = db_select('gf_stock_prices', 'p')
  ->fields('p', array('price_id', 'currency'))
  ->distinct('p.price_id' )
  ->execute()
  ->fetchAll();

foreach($query_region_ids as $name=>$region_id) {
  $region_ids[$region_id->price_id] = $region_id->price_id;
}

foreach(gf_stock_get_regions() as $name => $region){
  $options[$name] = $region;
  // Привязки имеющихся ID цен регионов к конкретным регионам.
  $form['gf_stock_region_prices']['gf_stock_region_price_'. $name] = array(
    '#type' => 'select',
    '#title' => t('Price ID for Region @region', array('@region' => drupal_strtoupper($name))),
    '#description' => t('The stock region that will be selected if the user did`t select their region.'),
    '#options' => $region_ids,
    '#default_value' => variable_get('gf_stock_region_price_' . $name),
  );
}

// Регион по-умолчанию. Когда пол-ль не выбирал никаких регионов.
$form['gf_stock_default_region'] = array(
  '#type' => 'select',
  '#title' => t('Default Region'),
  '#description' => t('The stock region that will be selected if the user did`t select their region.'),
  '#options' => $options,
  '#default_value' => variable_get('gf_stock_default_region', GF_STOCK_REGION_ALL),
  '#weight' => -1,
);
return system_settings_form($form);
}


/**
 * Implements hook_views_api().
 */
function gf_stock_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'gf_stock') . '/views',
  );
}

/**
 * Получение актуального курса юаня к рублю.
 */
function _gf_stock_get_yuan_exchange_rate() {
  $url_json = 'https://www.cbr-xml-daily.ru/daily_json.js';
  try {
    $data = json_decode(file_get_contents($url_json)); 
    $rate = ($data->Valute->CNY->Value / 10);
    $date = $data->Date;
  } catch(Exception $e) {
    watchdog('gf_stock', $e->getMessage(), array(), WATCHDOG_ERROR);
    return;
  }
  return array(
    'rate' => $rate, 
    'date' => $date
  );
}

/**
 * Обновление курса юаня, используемого при конвертациях на сайте.
 */
function gf_stock_update_yuan_exchange_rate() {
  if($data = _gf_stock_get_yuan_exchange_rate()){
    variable_set('gf_stock_yuan_exchange_rate', $data['rate'] );
    variable_set('gf_stock_yuan_rate_last_update', $data['date'] );
  }
}

/**
 * Implements hook_cron().
 *
 * Обновляем курс юаня к рублю по крону раз в сутки.
 */
function gf_stock_cron() {
  $last_update = variable_get('gf_stock_yuan_rate_last_update', 0);
  $time_passed = (REQUEST_TIME - strtotime($last_update));
  if ($time_passed > (60*60*24)) {
    gf_stock_update_yuan_exchange_rate();
  }
}


/**
 * Implements hook_uc_cart_alter().
 *
 * Правим цену в корзине в соответствии с регионом заказа
 */
function gf_stock_uc_cart_alter(&$items) {
  $region_stock = FALSE;
  foreach ($items as $key => $item) {
    $item->cost = $item->price;
    if ($region_stock == FALSE and $item->data["region_stock"]) {
      $region_stock = $item->data["region_stock"];
    }
    if ($region_stock == "Russia") {
      $item->price = $item->gf_region_prices["Russia"];
    } elseif ($region_stock == "China") {
      $item->price = round($item->gf_region_prices["China"]);
    }
  }
}


/**
 * Implements hook_uc_add_to_cart_data().
 */
function gf_stock_uc_add_to_cart_data($form_values) {
  if (isset($form_values['nid'])) {
    $node = node_load($form_values['nid']);
    return array(
      'shippable' => isset($node->shippable) ? $node->shippable : variable_get('uc_product_shippable_' . $node->type, 1),
      'type' => $node->type,
      'region_stock' => $_SESSION['gf_stock_region'],
    );
  }
  else {
    return array(
      'shippable' => variable_get('uc_product_shippable_product', 1),
      'type' => 'product',
      'region_stock' => $_SESSION['gf_stock_region'],
    );
  }
}

